# define data-split - folds for 6-fold cross validation
train:
    fold1:
        - 269
        - 292
        - 350
        - 356
        - 738
        - 771
        - 786
        - 806
        - 834
        - 855
        - 880
        - 890
        - 902
        - 931

    fold2:
        - 270
        - 294
        - 354
        - 739
        - 788
        - 796
        - 807
        - 835
        - 856
        - 863
        - 882
        - 891
        - 906
        - 932

    fold3:
        - 271
        - 295
        - 734
        - 749
        - 797
        - 808
        - 825
        - 840
        - 865
        - 883
        - 892
        - 907
        - 921
        - 922

    fold4:
        - 278
        - 745
        - 750
        - 760
        - 799
        - 809
        - 827
        - 841
        - 847
        - 866
        - 884
        - 895
        - 925

    fold5:
        - 279
        - 751
        - 764
        - 778
        - 801
        - 810
        - 828
        - 845
        - 849
        - 867
        - 886
        - 896
        - 926

    fold6:
        - 280
        - 768
        - 781
        - 784
        - 802
        - 817
        - 829
        - 846
        - 850
        - 868
        - 887
        - 898
        - 928
test:
  - 288
  - 770
  - 785
  - 804
  - 821
  - 830
  - 853
  - 857
  - 861
  - 871
  - 889
  - 899
  - 900
  - 901
  - 908
  - 909
  - 911
  - 929
  - 933
  - 934
